### PR TITLE
Ques 15, 16, 17, 18 Done

### PR DESCRIPTION
**Pull request by RohitChauhan98**
Check the code... If any changes required please let me know

### CODE REVIEW

**Comment by UtkarshDeoli** [comment]
Pr is Solving Issue : #3

**Review by UtkarshDeoli — CHANGES_REQUESTED** [review]
Hey Rohit Just checked the code all things seems good but Q15's main file has a curly bace missing please put that and recommit

**Comment by RohitChauhan98** [comment]
Thanks for Checking the code :)

**Comment by RohitChauhan98** [comment]
Hey! Please assign me some other question so i will commit the question and correction as well...

**Comment by UtkarshDeoli** [comment]
@RohitChauhan98  I will add C Practical Files Program and DSA End Term Programs ASAP after tahat i will assign some of them to you please Keep CHECKING ISSUES TAB

**Comment by RohitChauhan98** [comment]
Okay my friend...

**Comment by RohitChauhan98** [comment]
Please now Check the code and accept the pull request...

**Comment by UtkarshDeoli** [comment]
ok merging

**Pull request merged**
